apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.36
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password
                key: secretKey
        resources:
          requests:
            cpu: 256m
            memory: 512Mi
          limits:
            cpu: 256m 
            memory: 512Mi
        volumeMounts:
          - name: mysql-config-volume
            mountPath: /etc/mysql/conf.d/default_auth.cnf
            subPath: default_auth
          - name: mysql-pv-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-config-volume
          configMap:
            name: mysql-config
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        
        